# Generated by Django 3.2.23 on 2023-11-17 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(default=None, max_length=100)),
                ('Password', models.CharField(default=None, max_length=100)),
            ],
            options={
                'db_table': 'AdminDetails',
            },
        ),
        migrations.CreateModel(
            name='Hospitals_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(default=None, max_length=255)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_number', models.CharField(default=None, max_length=100)),
                ('specialties', models.CharField(blank=True, max_length=255, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('emergency_contact', models.CharField(default=None, max_length=100)),
                ('State', models.CharField(default=None, max_length=100)),
                ('City', models.CharField(default=None, max_length=100)),
                ('Area', models.CharField(default=None, max_length=100)),
            ],
            options={
                'db_table': 'Hospitals_Data',
            },
        ),
        migrations.CreateModel(
            name='loggedin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default=None, max_length=100)),
                ('Phone', models.CharField(default=None, max_length=100)),
                ('Email', models.CharField(default=None, max_length=100)),
                ('Username', models.CharField(default=None, max_length=100)),
                ('Password', models.CharField(default=None, max_length=100)),
                ('Address', models.CharField(default=None, max_length=100)),
                ('State', models.CharField(default=None, max_length=100)),
                ('City', models.CharField(default=None, max_length=100)),
            ],
            options={
                'db_table': 'loggedin',
            },
        ),
        migrations.CreateModel(
            name='Queries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_Id', models.CharField(default=None, max_length=100)),
                ('Query', models.CharField(default=None, max_length=100)),
            ],
            options={
                'db_table': 'Queries',
            },
        ),
    ]
